import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import Footer from './components/footer'
import Navigation from './components/navigation'
import './globals.css'

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body className="bg-zinc-900 w-full h-screen">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
